version: '3'

services:
  app_server:
    build: ./app_server
    ports:
      - "8000:8000"
    volumes:
      - ./app_server:/app
    working_dir: /app
    command: uvicorn app_server:app --host 0.0.0.0 --port 8001

  host:
    build: ./host
    depends_on:
      - app_server
    volumes:
      - ./host:/app
    working_dir: /app
    stdin_open: true
    tty: true
    command: python azure_openai_client.py
