[project]
name = "azure-openai-func-calling-with-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "arxiv>=2.2.0",
    "fastmcp[cli]>=2.10.5",
    "openai>=1.95.1",
]
